const endpointGroups = {
  Auth: [
    {
      group: 'Auth',
      method: 'POST',
      path: '/api/auth/register',
      auth: false,
      description: 'Register a new user account',
      body: {
        name: 'string  (required)',
        email: 'string  (required)',
        password: 'string  (required, min 6 chars)',
        age: 'number  (optional)',
        gender: '"male" | "female" | "other"  (optional)',
        phoneNumbers: 'string[]  (optional)',
        medicalHistories: 'string[]  (optional)',
        address: '{ city, street, gov }  (optional)',
      },
      response: { message: 'Registration successful' },
    },
    {
      group: 'Auth',
      method: 'POST',
      path: '/api/auth/login',
      auth: false,
      description: 'Login and receive a JWT token',
      body: {
        email: 'string  (required)',
        password: 'string  (required)',
      },
      response: { message: 'Login successful', token: '<jwt>', user: { id: '', name: '', email: '', age: '', gender: '', phoneNumbers: [], medicalHistories: [], address: { city: '', street: '', gov: '' }, profileImage: '', profileImageUrl: '' } },
    },
    {
      group: 'Auth',
      method: 'GET',
      path: '/api/auth/profile',
      auth: true,
      description: "Get the logged-in user's profile (password excluded)",
      body: null,
      response: { message: 'Profile retrieved successfully', user: { id: '', name: '', email: '', age: '', gender: '', phoneNumbers: [], medicalHistories: [], address: { city: '', street: '', gov: '' }, profileImage: '', profileImageUrl: '' } },
    },
    {
      group: 'Auth',
      method: 'PUT',
      path: '/api/auth/profile',
      auth: true,
      description: 'Update name, email, age, gender, and/or password',
      body: {
        name: 'string  (optional)',
        email: 'string  (optional)',
        age: 'number  (optional)',
        gender: '"male" | "female" | "other"  (optional)',
        password: 'string  (optional, min 6 chars)',
        phoneNumbers: 'string[]  (optional — replaces all phone numbers)',
        medicalHistories: 'string[]  (optional — replaces all medical histories)',
        address: '{ city?, street?, gov? }  (optional — merges into existing address)',
      },
      response: { message: 'Profile updated successfully', user: { id: '', name: '', email: '', age: '', gender: '', phoneNumbers: [], medicalHistories: [], address: { city: '', street: '', gov: '' }, profileImage: '', profileImageUrl: '' } },
    },
    {
      group: 'Auth',
      method: 'PUT',
      path: '/api/auth/change-password',
      auth: true,
      description: 'Change the logged-in user\'s password by verifying the current password first',
      body: {
        currentPassword: 'string  (required)',
        newPassword: 'string  (required, min 6 chars)',
      },
      response: { message: 'Password changed successfully' },
    },
    {
      group: 'Auth',
      method: 'POST',
      path: '/api/auth/profile/image',
      auth: true,
      description: 'Upload or replace the logged-in user\'s profile image',
      body: { type: 'multipart/form-data', fields: { image: 'image file (jpeg/jpg/png/gif/webp, max 5 MB)' } },
      response: { message: 'Profile image uploaded successfully', user: { id: '', name: '', email: '', age: '', gender: '', phoneNumbers: [], medicalHistories: [], address: { city: '', street: '', gov: '' }, profileImage: '', profileImageUrl: '' } },
    },
    {
      group: 'Auth',
      method: 'GET',
      path: '/api/auth/profile/image',
      auth: true,
      description: 'Download the logged-in user\'s profile image',
      body: null,
      response: 'Binary file download',
    },
  ],
  Diagnosis: [
    {
      group: 'Diagnosis',
      method: 'POST',
      path: '/api/diagnosis',
      auth: true,
      description: 'Upload one dental image, save input under uploads/diagnosis/input and any AI-generated image under uploads/diagnosis/output',
      body: { type: 'multipart/form-data', fields: { image: 'image file (jpeg / jpg / png / gif / webp, max 10 MB)' } },
      response: {
        message: 'Diagnosis completed',
        diagnosis: {
          inputImagePath: 'diagnosis/input/<filename>',
          outputImagePath: 'diagnosis/output/<filename>',
          inputImageUrl: '/uploads/diagnosis/input/<filename>',
          outputImageUrl: '/uploads/diagnosis/output/<filename>',
          detectionResults: 'Any base64 image from the AI response is replaced with a saved /uploads/... path',
        },
      },
    },
    {
      group: 'Diagnosis',
      method: 'POST',
      path: '/api/diagnosis/batch',
      auth: true,
      description: 'Upload up to 10 images and store input/output image paths for each diagnosis',
      body: { type: 'multipart/form-data', fields: { images: 'up to 10 image files (jpeg/jpg/png/gif/webp, max 10 MB each)' } },
      response: {
        message: 'Batch diagnosis completed',
        count: 0,
        diagnoses: [
          {
            inputImagePath: 'diagnosis/input/<filename>',
            outputImagePath: 'diagnosis/output/<filename>',
            inputImageUrl: '/uploads/diagnosis/input/<filename>',
            outputImageUrl: '/uploads/diagnosis/output/<filename>',
          },
        ],
      },
    },
    {
      group: 'Diagnosis',
      method: 'GET',
      path: '/api/diagnosis/history',
      auth: true,
      description: 'Retrieve all past diagnoses for the logged-in user with saved input/output image paths',
      body: null,
      response: {
        count: 0,
        diagnoses: [
          {
            inputImagePath: 'diagnosis/input/<filename>',
            outputImagePath: 'diagnosis/output/<filename>',
            inputImageUrl: '/uploads/diagnosis/input/<filename>',
            outputImageUrl: '/uploads/diagnosis/output/<filename>',
          },
        ],
      },
    },
  ],
  Chat: [
    {
      group: 'Chat',
      method: 'POST',
      path: '/api/chat',
      auth: true,
      description: 'Ask the AI and persist the conversation in a ChatSession. You can continue via session_id or bind the chat to a diagnosis via diagnosis_id.',
      body: {
        question: 'string  (required)',
        context: 'string  (optional — additional context for direct chat)',
        diagnosis_id: 'string(ObjectId)  (optional — use diagnosis report as context)',
        session_id: 'string(ObjectId)  (optional — continue an existing chat session)',
      },
      response: {
        session_id: 'string(ObjectId)',
        diagnosis_id: 'string(ObjectId) | null',
        last_active: 'ISO date string',
        answer: 'string',
        raw: {},
      },
    },
    {
      group: 'Chat',
      method: 'GET',
      path: '/api/chat/sessions',
      auth: true,
      description: 'Return all chat sessions for the logged-in user, including stored question/answer messages.',
      body: null,
      response: {
        count: 0,
        sessions: [
          {
            _id: 'string(ObjectId)',
            user_id: 'string(ObjectId)',
            diagnosis_id: 'string(ObjectId) | null',
            message: [{ question: 'string', answer: 'string', created_at: 'ISO date string' }],
            last_active: 'ISO date string',
          },
        ],
      },
    },
    {
      group: 'Chat',
      method: 'GET',
      path: '/api/chat/sessions/:session_id',
      auth: true,
      description: 'Return one chat session by id for the logged-in user, including stored question/answer messages.',
      body: null,
      response: {
        session: {
          _id: 'string(ObjectId)',
          user_id: 'string(ObjectId)',
          diagnosis_id: 'string(ObjectId) | null',
          message: [{ question: 'string', answer: 'string', created_at: 'ISO date string' }],
          last_active: 'ISO date string',
        },
      },
    },
  ],
  Doc: [
    {
      group: 'Doc',
      method: 'GET',
      path: '/api/doc',
      auth: false,
      description: 'List all available API endpoints with descriptions and body shapes',
      body: null,
      response: { title: '', version: '', base_url: '', endpoints: [] },
    },
  ],
};

const buildApiDocs = (baseUrl) => ({
  title: 'Smart Dental AI — API Reference',
  version: '1.0.0',
  base_url: baseUrl,
  note: 'Endpoints marked with auth:true require the header  Authorization: Bearer <token>',
  groupedEndpoints: endpointGroups,
});

module.exports = {
  buildApiDocs,
};
